# Generated by Django 4.1.3 on 2023-04-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Google'), (2, 'Facebook')], default=0, verbose_name='Auth type'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Social Image choice'),
        ),
    ]
