# Generated by Django 4.1.3 on 2023-04-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_auth_type_user_social_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAuthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=150, verbose_name='Social id')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
        ),
    ]
