# Generated by Django 4.1.3 on 2023-04-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_socialauthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialauthdata',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
