# Generated by Django 4.1.3 on 2023-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_socialauthdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialauthdata',
            name='signup_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Signup data'),
        ),
    ]
