# Generated by Django 4.1.3 on 2023-04-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_country_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Social Image url'),
        ),
    ]
