# Generated by Django 4.1.3 on 2023-08-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliate_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Affiliate ID'),
        ),
    ]
