# Generated by Django 4.1.3 on 2023-02-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_alter_mainmenu_options_mainmenu_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={},
        ),
    ]
