# Generated by Django 4.1.3 on 2023-02-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_alter_mainmenu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='mainmenu',
            old_name='sort_order',
            new_name='order',
        ),
    ]
