# Generated by Django 4.1.3 on 2023-02-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_alter_mainmenu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={},
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='order',
        ),
    ]
