# Generated by Django 4.1.3 on 2023-02-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_alter_mainmenu_options_remove_mainmenu_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenuitem',
            name='sort_order',
            field=models.SmallIntegerField(default=0, verbose_name='Sort order'),
        ),
    ]
