# Generated by Django 4.1.3 on 2023-02-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_alter_mainmenuitem_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='sort_order',
            field=models.SmallIntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
