# Generated by Django 4.1.3 on 2023-02-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_mainmenu_sort_order_alter_mainmenuitem_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ('sort_order',)},
        ),
    ]
