# Generated by Django 4.1.3 on 2023-02-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('utility', '0008_alter_mainmenu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenuitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Company'),
        ),
    ]
