# Generated by Django 4.1.3 on 2023-02-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0010_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Link'),
        ),
    ]
