# Generated by Django 4.1.3 on 2023-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0012_footermenu_footermenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_2', models.CharField(max_length=2, verbose_name='Alpha 2')),
                ('alpha_3', models.CharField(max_length=3, verbose_name='Alpha 3')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('official_name', models.CharField(max_length=150, verbose_name='Official name')),
            ],
        ),
    ]
