# Generated by Django 4.1.3 on 2023-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0013_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Official name'),
        ),
    ]
