# Generated by Django 4.1.3 on 2023-03-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_articledetailpage_body_and_more'),
        ('utility', '0014_alter_country_official_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenuitem',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.companydetail', verbose_name='Company'),
        ),
    ]
