# Generated by Django 4.1.3 on 2023-03-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0017_mainmenuitem_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenuitem',
            name='company',
        ),
    ]
