# Generated by Django 4.1.3 on 2023-04-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0019_socialmediasettings_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email'),
        ),
    ]
