# Generated by Django 4.1.3 on 2023-04-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0020_globalsetting_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full name')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Is replied?')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
            ],
        ),
    ]
