# Generated by Django 4.1.3 on 2023-06-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0021_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermenu',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='footermenuitem',
            name='link_title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='link_title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainmenuitem',
            name='link_title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title en'),
        ),
    ]
