# Generated by Django 4.1.3 on 2023-06-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('utility', '0022_footermenu_title_en_footermenuitem_link_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
