# Generated by Django 4.1.3 on 2023-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0023_story_image_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='address_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Address en'),
        ),
    ]
