# Generated by Django 4.1.3 on 2023-07-27 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0024_globalsetting_address_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
            ],
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('language', models.IntegerField(choices=[(0, 'English'), (1, 'Arabic')], default=0, verbose_name='Language')),
                ('type', models.IntegerField(choices=[(0, 'Link'), (1, 'Banner')], default=0, verbose_name='Creative type')),
                ('size', models.IntegerField(choices=[(0, 'Unavailable'), (1, '1920 x 1080'), (2, '1440 x 780')], default=0, verbose_name='Creative size')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.brand', verbose_name='Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identification', models.CharField(blank=True, max_length=50, null=True, verbose_name='User id')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Registration date')),
                ('afp', models.CharField(blank=True, max_length=150, null=True, verbose_name='AFP')),
                ('status', models.IntegerField(choices=[(0, 'Answer'), (1, 'No Answer'), (2, 'Interested'), (3, 'Not Interested'), (4, 'Wrong Number')], default=0, verbose_name='User status')),
                ('qftd', models.IntegerField(default=0, verbose_name='QFTD')),
                ('qualification_date', models.DateTimeField(blank=True, null=True, verbose_name='Qualification date')),
                ('position_count', models.IntegerField(default=0, verbose_name='Position count')),
                ('first_deposit', models.FloatField(default=0, verbose_name='First Deposit')),
                ('first_deposit_date', models.DateTimeField(blank=True, null=True, verbose_name='First deposit date')),
                ('net_deposits', models.FloatField(default=0, verbose_name='Net Deposit')),
                ('deposit_count', models.IntegerField(default=0, verbose_name='Deposit count')),
                ('account_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account ID')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Customer name')),
                ('commission', models.FloatField(default=0, verbose_name='Commission')),
                ('visitor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('visit_count', models.IntegerField(default=1, verbose_name='Visit Count')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.country', verbose_name='Country')),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.creative', verbose_name='Creative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
