# Generated by Django 4.1.3 on 2023-07-31 18:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('affiliate', '0002_alter_analytics_country_alter_analytics_creative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Template name')),
                ('file_name', models.CharField(max_length=150, verbose_name='File name')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.brand', verbose_name='Brand')),
                ('preview_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='creative',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.template', verbose_name='Tempalate'),
        ),
    ]
