# Generated by Django 4.1.3 on 2023-07-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_template_creative_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time'),
        ),
    ]
