# Generated by Django 4.1.3 on 2023-08-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_template_creation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creative',
            options={'ordering': ('-creation_time',)},
        ),
    ]
