# Generated by Django 4.1.3 on 2023-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0006_alter_analytics_status_alter_analytics_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Is Registered?'),
        ),
    ]
