# Generated by Django 4.1.3 on 2023-08-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0007_analytics_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='visitor_country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Visitor country'),
        ),
    ]
