FROM python:3.10
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE=alltargeting.settings.dev
WORKDIR /app/server/
COPY ./server /app/server/
COPY ./server/requirements /app/server/
RUN pip install --upgrade pip
RUN pip install -r requirements/dev.txt
