# Generated by Django 4.1.3 on 2023-02-26 18:47

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('broker_survey_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('subtitle', wagtail.blocks.CharBlock(max_length=250)), ('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('learn_more_button_text', wagtail.blocks.CharBlock(max_length=250)), ('learn_more_button_link', wagtail.blocks.CharBlock(max_length=250)), ('survey_button_text', wagtail.blocks.CharBlock(max_length=250)), ('survey_button_link', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_keywords',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords'),
        ),
    ]
