# Generated by Django 4.1.3 on 2023-02-27 00:38

from django.db import migrations
import home.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_og_image_homepage_og_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('broker_survey_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('subtitle', wagtail.blocks.CharBlock(max_length=250)), ('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('learn_more_button_text', wagtail.blocks.CharBlock(max_length=250)), ('learn_more_button_link', wagtail.blocks.CharBlock(max_length=250)), ('survey_button_text', wagtail.blocks.CharBlock(max_length=250)), ('survey_button_link', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
