# Generated by Django 4.1.3 on 2023-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_redirectpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectpage',
            name='is_company_page',
            field=models.BooleanField(default=False, verbose_name='Is company page?'),
        ),
    ]
