# Generated by Django 4.1.3 on 2023-02-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_redirectpage_is_company_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirectpage',
            name='is_company_page',
        ),
    ]
