# Generated by Django 4.1.3 on 2023-02-27 18:44

import company.models
import company.serializers
from django.db import migrations
import home.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_articledetailpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('broker_survey_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('subtitle', wagtail.blocks.CharBlock(max_length=250)), ('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('learn_more_button_text', wagtail.blocks.CharBlock(max_length=250)), ('learn_more_button_link', wagtail.blocks.CharBlock(max_length=250)), ('survey_button_text', wagtail.blocks.CharBlock(max_length=250)), ('survey_button_link', wagtail.blocks.CharBlock(max_length=250))])), ('companies', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('companies', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('company', home.blocks.SnippetChooserBlock(serializer=company.serializers.HomeCompanySerializer, target_model=company.models.Company))])))])), ('news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('news', wagtail.blocks.ListBlock(home.blocks.NewsDetailPageChooserBlock(page_type=['home.NewsDetailPage'])))])), ('articles', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('news', wagtail.blocks.ListBlock(home.blocks.ArticleDetailPageChooserBlock(page_type=['home.ArticleDetailPage'])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
