# Generated by Django 4.1.3 on 2023-02-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdetailpage',
            name='short_desc',
        ),
    ]
