# Generated by Django 4.1.3 on 2023-02-28 17:58

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
        ('home', '0017_remove_newsdetailpage_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_keywords', models.CharField(blank=True, max_length=550, null=True, verbose_name='Og keywords')),
                ('body', wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock())])), ('image', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))]))], blank=True, null=True, use_json_field=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
