# Generated by Django 4.1.3 on 2023-03-07 09:55

from django.db import migrations
import home.blocks
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_companydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock())])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock())])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
