# Generated by Django 4.1.3 on 2023-03-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0014_alter_country_official_name'),
        ('home', '0025_alter_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='main_branch',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='origin_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='utility.country', verbose_name='Main branch'),
        ),
    ]
