# Generated by Django 4.1.3 on 2023-03-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_companydetail_main_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
    ]
