# Generated by Django 4.1.3 on 2023-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_articledetailpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='fees_rating',
            field=models.FloatField(default=0, verbose_name='Fees rating'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='leverage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Leverage'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='markets_products',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Market products'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='security_rating',
            field=models.FloatField(default=0, verbose_name='Security rating'),
        ),
    ]
