# Generated by Django 4.1.3 on 2023-03-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_companydetail_fees_rating_companydetail_leverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='recommendation_text',
            field=models.TextField(blank=True, null=True, verbose_name='Recommendation text'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='markets_products',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Market and products'),
        ),
    ]
