# Generated by Django 4.1.3 on 2023-04-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_articledetailpage_post_on_social_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='already_published',
            field=models.BooleanField(default=False, verbose_name='Is already published?'),
        ),
    ]
