# Generated by Django 4.1.3 on 2023-04-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_articledetailpage_already_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetailpage',
            name='already_published',
        ),
    ]
