# Generated by Django 4.1.3 on 2023-06-03 06:22

from django.db import migrations, models
import home.blocks
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_homepage_title_en_alter_articledetailpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='privatepage',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='redirectpage',
            name='hero_description_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Hero description en'),
        ),
        migrations.AddField(
            model_name='redirectpage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero title en'),
        ),
        migrations.AddField(
            model_name='redirectpage',
            name='list_title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='List title en'),
        ),
        migrations.AddField(
            model_name='redirectpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articledetailpage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock())])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock())])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock())])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock())])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock())])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('company_evaluation_block', home.blocks.CompanyEvaluationBlock()), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock())])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock())])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='privatepage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock())])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock())])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
