# Generated by Django 4.1.3 on 2023-06-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_basicpage_title_en_privatepage_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero subtitle en'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hero title en'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
