# Generated by Django 4.1.3 on 2023-06-08 00:04

import company.models
import company.serializers
from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0051_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='thumbnail_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='thumbnail_image_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='background_image_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='thumbnail_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='articledetailpage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock(required=False))])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock(required=False))])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock(required=False))])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock(required=False))])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock(required=False))])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('company_evaluation_block', home.blocks.CompanyEvaluationBlock()), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('broker_survey_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('subtitle', wagtail.blocks.CharBlock(max_length=250)), ('subtitle_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('learn_more_button_text', wagtail.blocks.CharBlock(max_length=250)), ('learn_more_button_text_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('learn_more_button_link', wagtail.blocks.CharBlock(max_length=250)), ('survey_button_text', wagtail.blocks.CharBlock(max_length=250)), ('survey_button_text_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('survey_button_link', wagtail.blocks.CharBlock(max_length=250))])), ('companies', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('company', wagtail.blocks.ListBlock(home.blocks.CompanyListChooserBlock(page_type=['home.CompanyDetail'])))])), ('news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('news', wagtail.blocks.ListBlock(home.blocks.NewsDetailPageChooserBlock(page_type=['home.NewsDetailPage'])))])), ('articles', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('articles', wagtail.blocks.ListBlock(home.blocks.ArticleDetailPageChooserBlock(page_type=['home.ArticleDetailPage'])))])), ('two_column_text_image_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('description', home.blocks.RichTextBlock()), ('description_en', home.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock(required=False))])), ('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('currency_rate_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('tabs', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('stocks', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('stock', home.blocks.SnippetChooserBlock(serializer=company.serializers.StockSerializer, target_model=company.models.Stock))])))])))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock(required=False))])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock(required=False))])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='privatepage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock(required=False))])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock(required=False))])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
