# Generated by Django 4.1.3 on 2023-07-10 05:40

from django.db import migrations
import home.blocks
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_privatepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetailpage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock(required=False))])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock(required=False))])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('custom_table_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('table_en', wagtail.contrib.table_block.blocks.TableBlock())])), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock(required=False))])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock(required=False))])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('custom_table_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('table_en', wagtail.contrib.table_block.blocks.TableBlock())])), ('company_evaluation_block', home.blocks.CompanyEvaluationBlock()), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.StructBlock([('desc', home.blocks.RichTextBlock()), ('desc_en', home.blocks.RichTextBlock(required=False))])), ('button_block', wagtail.blocks.StructBlock([('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))])), ('label', wagtail.blocks.CharBlock()), ('label_en', wagtail.blocks.CharBlock(required=False))])), ('image_block', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'}))])), ('banner', wagtail.blocks.StructBlock([('image', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('image_en', home.blocks.ImageChooserBlock(rendition_rules={'original': 'original|jpegquality-60|format-webp'})), ('link', wagtail.blocks.StreamBlock([('page', home.blocks.PageChooserBlock(max_num=1)), ('link', wagtail.blocks.URLBlock(max_num=1))]))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock()), ('custom_table_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('table_en', wagtail.contrib.table_block.blocks.TableBlock())])), ('video_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=False)), ('title_en', wagtail.blocks.CharBlock(max_length=250, required=False)), ('youtube_video_id', wagtail.blocks.CharBlock(max_length=250))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
