# Generated by Django 4.1.3 on 2023-09-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_articledetailpage_body_alter_basicpage_body_and_more'),
        ('home', '0055_alter_author_id_alter_category_id_and_more'),
    ]

    operations = [
    ]
