# Generated by Django 4.1.3 on 2023-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
    ]
