# Generated by Django 4.1.3 on 2023-02-27 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('company', '0002_alter_company_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_open_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Account open link'),
        ),
        migrations.AddField(
            model_name='company',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_islamic',
            field=models.BooleanField(default=False, verbose_name='Is islamic account?'),
        ),
    ]
