# Generated by Django 4.1.3 on 2023-02-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_account_open_link_company_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('creation_time',)},
        ),
    ]
