# Generated by Django 4.1.3 on 2023-03-10 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_companydetail_body'),
        ('company', '0007_alter_ratingreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreview',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='home.companydetail', verbose_name='Company'),
        ),
    ]
